name: JoinLeavePlus
version: ${project.version}
main: me.abradee.joinLeavePlus.JoinLeavePlus
api-version: '1.21'
authors: [ abradee ]
description: Plugin that changes the join/leave messages with a configured message.
website: https://modrinth.com/plugins/joinleaveplus

commands:
  about-joinleaveplus:
    description: A command that displays a detailed about message about the plugin to the executor.
    usage: /<command>