#    __     _     __                    _____ _
# __|  |___|_|___|  |   ___ ___ _ _ ___|  _  | |_ _ ___
#|  |  | . | |   |  |__| -_| .'| | | -_|   __| | | |_ -|
#|_____|___|_|_|_|_____|___|__,|\_/|___|__|  |_|___|___|
# v1.2
# developed by abradee
# (c) 2020-2026 abradee
# (c) 2025-2026 JoinLeavePlus under GPL-3.0 license

# Configure your join and leave messages here!
# Note: supports EITHER MiniMessage or legacy formatting
first-time-join: "<gold><b>[+] </b><aqua>%player% <yellow>joined for the first time!"
join: "<green><b>[+] </b><green>%player% <gray>has joined."
leave: "<red><b>[-] </b><red>%player% <gray>has left."